server:
  port: 9193
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://localhost:9411/
logging:
  file:
    name: /Users/anicet/project/hands-lab-java/archive/microservice.log
